#!/usr/bin/env bash
# Shared configuration sourced by the Sparkle release scripts.
# Override any of these by exporting them before invoking a script, or by
# setting them in .env.release.local (sourced by local-release-build.sh).

SPARKLE_VERSION="${SPARKLE_VERSION:-2.9.2}"

# Keychain account that holds the EdDSA private key. Generated by Sparkle's
# `generate_keys` and used by `sign_update` / `generate_appcast`. Forks should
# replace this with their own bundle id.
SPARKLE_KEY_ACCOUNT="${SPARKLE_KEY_ACCOUNT:-com.nfarina.SonosControl}"

# Where the appcast is hosted (e.g. GitHub Pages site for this repo). The
# appcast URL is this with /appcast.xml appended (or override SPARKLE_FEED_URL).
SPARKLE_SITE_URL="${SPARKLE_SITE_URL:-https://nfarina.github.io/sonos-control}"
SPARKLE_FEED_URL="${SPARKLE_FEED_URL:-${SPARKLE_SITE_URL%/}/appcast.xml}"

# GitHub release URLs.
SPARKLE_RELEASES_URL="${SPARKLE_RELEASES_URL:-https://github.com/nfarina/sonos-control/releases}"
SPARKLE_RELEASE_DOWNLOAD_BASE_URL="${SPARKLE_RELEASE_DOWNLOAD_BASE_URL:-https://github.com/nfarina/sonos-control/releases/download}"

# Sparkle CLI tools are downloaded as a release asset and cached.
SPARKLE_TOOLS_REPO="${SPARKLE_TOOLS_REPO:-sparkle-project/Sparkle}"
SPARKLE_TOOLS_ARCHIVE="${SPARKLE_TOOLS_ARCHIVE:-Sparkle-${SPARKLE_VERSION}.tar.xz}"
SPARKLE_TOOLS_CACHE_DIR="${SPARKLE_TOOLS_CACHE_DIR:-build/sparkle-tools/${SPARKLE_VERSION}}"
